name: cafesense
description: CafeSense - Smart Coffee Shop Recommendation App
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  smooth_page_indicator: ^1.1.0
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  flutter_riverpod: ^2.5.1
  shared_preferences: ^2.2.3
  dio: ^5.4.0
  geolocator: ^14.0.2
  easy_localization: ^3.0.3
  firebase_core: ^4.9.0
  cloud_firestore: ^6.4.1
  firebase_auth: ^6.5.1
  panorama_viewer: ^2.0.7
  package_info_plus: 9.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/translations/
